/**
 * Turns the legal texts into a TypeScript module.
 *
 * They are authored once in `store/legal` and shipped to the stores from there, and the
 * website has to render exactly those files — a second copy would drift away from the
 * submitted version.
 *
 * Reading them with `readFileSync` at build time looked like it did that, and it did not:
 * a file outside the module graph is invisible to webpack, so Next reused the previously
 * prerendered page and the site kept serving the old imprint after the source had already
 * changed. That failed silently, which for a legal page is the worst way to fail.
 *
 * Generating a module makes the content part of the graph. Change the markdown, the
 * module changes, the cache key changes, the page is rebuilt.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const LEGAL_DIR = join(here, '..', '..', '..', 'store', 'legal');
const OUT = join(here, '..', 'src', 'generated', 'legal.ts');

const FILES = {
  impressum: 'impressum.de.md',
  datenschutz: 'datenschutz.de.md',
  agb: 'agb.de.md',
};

const entries = Object.entries(FILES).map(([slug, file]) => {
  const source = readFileSync(join(LEGAL_DIR, file), 'utf8').replace(/\r\n/g, '\n');
  return `  ${slug}: ${JSON.stringify(source)},`;
});

const module = `// Generated by scripts/generate-legal.mjs from store/legal. Do not edit by hand.
// Regenerate with \`pnpm --filter @lexipulse/web build\` or \`node scripts/generate-legal.mjs\`.

export const LEGAL_SOURCES = {
${entries.join('\n')}
} as const;

export type LegalSlug = keyof typeof LEGAL_SOURCES;
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, module, 'utf8');

const bytes = Buffer.byteLength(module, 'utf8');
console.log(`legal.ts written: ${Object.keys(FILES).length} Dokumente, ${bytes} Bytes`);
